set(DVP_CAMERA_DEVICE_FILES "")
set(DVP_CAMERA_PATH src/dvp)

if (CONFIG_DVP_CAMERA)
	list(APPEND DVP_CAMERA_DEVICE_FILES ${DVP_CAMERA_PATH}/dvp_sensor_devices.c)

if (CONFIG_DVP_GC0308)
	list(APPEND DVP_CAMERA_DEVICE_FILES ${DVP_CAMERA_PATH}/dvp_gc0308.c)
	list(APPEND GLOBAL_FUNCTION_SYMBOLS "gc0308_detect_sensor")
endif()

if (CONFIG_DVP_GC0328C)
	list(APPEND DVP_CAMERA_DEVICE_FILES ${DVP_CAMERA_PATH}/dvp_gc0328c.c)
	list(APPEND GLOBAL_FUNCTION_SYMBOLS "gc0328c_detect_sensor")
endif()

if (CONFIG_DVP_GC2145)
	list(APPEND DVP_CAMERA_DEVICE_FILES ${DVP_CAMERA_PATH}/dvp_gc2145.c)
	list(APPEND GLOBAL_FUNCTION_SYMBOLS "gc2145_detect_sensor")
endif()

if (CONFIG_DVP_HM1055)
	list(APPEND DVP_CAMERA_DEVICE_FILES ${DVP_CAMERA_PATH}/dvp_hm1055.c)
	list(APPEND GLOBAL_FUNCTION_SYMBOLS "hm1055_detect_sensor")
endif()

if (CONFIG_DVP_OV2640)
	list(APPEND DVP_CAMERA_DEVICE_FILES ${DVP_CAMERA_PATH}/dvp_ov2640.c)
	list(APPEND GLOBAL_FUNCTION_SYMBOLS "ov2640_detect_sensor")
endif()

if (CONFIG_DVP_SC101)
	list(APPEND DVP_CAMERA_DEVICE_FILES ${DVP_CAMERA_PATH}/dvp_sc101.c)
	list(APPEND GLOBAL_FUNCTION_SYMBOLS "sc101_detect_sensor")
endif()
endif()