/*
 * Copyright (c) 2026
 *
 * bk_video_player thread configuration.
 *
 * These macros expose thread priority and stack size to Kconfig so that users can
 * tune runtime stability (stack overflow) and scheduling latency without modifying code.
 *
 * Notes:
 * - Stack size unit: bytes.
 * - Priority: RTOS thread priority number (smaller/higher depends on RTOS implementation).
 */

#pragma once

#include "os/os.h"

/* Container parse threads */
#ifdef CONFIG_BK_VIDEO_PLAYER_VIDEO_PARSE_THREAD_PRIORITY
#define BK_VP_VIDEO_PARSE_THREAD_PRIORITY      (CONFIG_BK_VIDEO_PLAYER_VIDEO_PARSE_THREAD_PRIORITY)
#else
#define BK_VP_VIDEO_PARSE_THREAD_PRIORITY      (BEKEN_DEFAULT_WORKER_PRIORITY)
#endif

#ifdef CONFIG_BK_VIDEO_PLAYER_VIDEO_PARSE_THREAD_STACK_SIZE
#define BK_VP_VIDEO_PARSE_THREAD_STACK_SIZE    (CONFIG_BK_VIDEO_PLAYER_VIDEO_PARSE_THREAD_STACK_SIZE)
#else
#define BK_VP_VIDEO_PARSE_THREAD_STACK_SIZE    (8 * 1024)
#endif

#ifdef CONFIG_BK_VIDEO_PLAYER_AUDIO_PARSE_THREAD_PRIORITY
#define BK_VP_AUDIO_PARSE_THREAD_PRIORITY      (CONFIG_BK_VIDEO_PLAYER_AUDIO_PARSE_THREAD_PRIORITY)
#else
#define BK_VP_AUDIO_PARSE_THREAD_PRIORITY      (BEKEN_DEFAULT_WORKER_PRIORITY)
#endif

#ifdef CONFIG_BK_VIDEO_PLAYER_AUDIO_PARSE_THREAD_STACK_SIZE
#define BK_VP_AUDIO_PARSE_THREAD_STACK_SIZE    (CONFIG_BK_VIDEO_PLAYER_AUDIO_PARSE_THREAD_STACK_SIZE)
#else
#define BK_VP_AUDIO_PARSE_THREAD_STACK_SIZE    (8 * 1024)
#endif

/* Decode threads */
#ifdef CONFIG_BK_VIDEO_PLAYER_AUDIO_DECODE_THREAD_PRIORITY
#define BK_VP_AUDIO_DECODE_THREAD_PRIORITY     (CONFIG_BK_VIDEO_PLAYER_AUDIO_DECODE_THREAD_PRIORITY)
#else
#define BK_VP_AUDIO_DECODE_THREAD_PRIORITY     (BEKEN_DEFAULT_WORKER_PRIORITY)
#endif

#ifdef CONFIG_BK_VIDEO_PLAYER_AUDIO_DECODE_THREAD_STACK_SIZE
#define BK_VP_AUDIO_DECODE_THREAD_STACK_SIZE   (CONFIG_BK_VIDEO_PLAYER_AUDIO_DECODE_THREAD_STACK_SIZE)
#else
#define BK_VP_AUDIO_DECODE_THREAD_STACK_SIZE   (8 * 1024)
#endif

#ifdef CONFIG_BK_VIDEO_PLAYER_VIDEO_DECODE_THREAD_PRIORITY
#define BK_VP_VIDEO_DECODE_THREAD_PRIORITY     (CONFIG_BK_VIDEO_PLAYER_VIDEO_DECODE_THREAD_PRIORITY)
#else
#define BK_VP_VIDEO_DECODE_THREAD_PRIORITY     (BEKEN_DEFAULT_WORKER_PRIORITY)
#endif

#ifdef CONFIG_BK_VIDEO_PLAYER_VIDEO_DECODE_THREAD_STACK_SIZE
#define BK_VP_VIDEO_DECODE_THREAD_STACK_SIZE   (CONFIG_BK_VIDEO_PLAYER_VIDEO_DECODE_THREAD_STACK_SIZE)
#else
#define BK_VP_VIDEO_DECODE_THREAD_STACK_SIZE   (8 * 1024)
#endif

/* Event notify thread (vp_evt) */
#ifdef CONFIG_BK_VIDEO_PLAYER_EVENT_THREAD_PRIORITY
#define BK_VP_EVENT_THREAD_PRIORITY            (CONFIG_BK_VIDEO_PLAYER_EVENT_THREAD_PRIORITY)
#else
#define BK_VP_EVENT_THREAD_PRIORITY            (BEKEN_DEFAULT_WORKER_PRIORITY)
#endif

#ifdef CONFIG_BK_VIDEO_PLAYER_EVENT_THREAD_STACK_SIZE
#define BK_VP_EVENT_THREAD_STACK_SIZE          (CONFIG_BK_VIDEO_PLAYER_EVENT_THREAD_STACK_SIZE)
#else
#define BK_VP_EVENT_THREAD_STACK_SIZE          (4 * 1024)
#endif


